return {}
-- return {
--   "monaqa/dial.nvim",
--   opts = function(_, opts)
--     -- Override dial functions to check buffer modifiability
--     local dial = require("dial.map")
--     local original_inc_normal = dial.inc_normal
--     local original_dec_normal = dial.dec_normal
--
--     -- Wrap dial functions with modifiable check
--     dial.inc_normal = function(...)
--       if not vim.bo.modifiable or vim.bo.buftype == "terminal" then
--         return
--       end
--       return original_inc_normal(...)
--     end
--
--     dial.dec_normal = function(...)
--       if not vim.bo.modifiable or vim.bo.buftype == "terminal" then
--         return
--       end
--       return original_dec_normal(...)
--     end
--
--     return opts
--   end,
-- }

