# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":lastmonth"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%x"
          locale: "pt-BR"

  - trigger: ":mail"
    replace: "henrique.zambonin@gmail.com"
    # replace: "{{primaryEmail}}"
    # vars:
    #   - name: primaryEmail
    #     type: shell
    #     params:
    #       cmd: "echo $PRIMARY_EMAIL"
  - trigger: ":f@r"
    replace: "Forgotten@Rheinland"
