/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_blank_line_token1 = 1,
  anon_sym_EQ = 2,
  sym_export_keyword = 3,
  sym_key = 4,
  sym_decorator_comment = 5,
  sym_ignored_decorator_comment = 6,
  sym_plain_comment = 7,
  sym_divider = 8,
  aux_sym_unquoted_string_token1 = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_double_quoted_string_token1 = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_single_quoted_string_token1 = 13,
  anon_sym_BQUOTE = 14,
  aux_sym_backtick_quoted_string_token1 = 15,
  sym_escape_sequence = 16,
  sym_triple_backtick_string = 17,
  sym_triple_double_quoted_string = 18,
  sym_multiline_double_quoted_string = 19,
  sym_multiline_single_quoted_string = 20,
  anon_sym_DOLLAR_LBRACE = 21,
  anon_sym_COLON_DASH = 22,
  aux_sym_expansion_token1 = 23,
  anon_sym_RBRACE = 24,
  anon_sym_DOLLAR_LPAREN = 25,
  aux_sym_expansion_token2 = 26,
  anon_sym_RPAREN = 27,
  anon_sym_DOLLAR = 28,
  sym_identifier = 29,
  sym_source_file = 30,
  sym_blank_line = 31,
  sym_config_item = 32,
  sym__comment_line = 33,
  sym_comment_block = 34,
  sym__value = 35,
  sym_unquoted_string = 36,
  sym_quoted_string = 37,
  sym_double_quoted_string = 38,
  sym_single_quoted_string = 39,
  sym_backtick_quoted_string = 40,
  sym_multiline_string = 41,
  sym_expansion = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_comment_block_repeat1 = 44,
  aux_sym_unquoted_string_repeat1 = 45,
  aux_sym_double_quoted_string_repeat1 = 46,
  aux_sym_single_quoted_string_repeat1 = 47,
  aux_sym_backtick_quoted_string_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_blank_line_token1] = "blank_line_token1",
  [anon_sym_EQ] = "=",
  [sym_export_keyword] = "export_keyword",
  [sym_key] = "key",
  [sym_decorator_comment] = "decorator_comment",
  [sym_ignored_decorator_comment] = "ignored_decorator_comment",
  [sym_plain_comment] = "plain_comment",
  [sym_divider] = "divider",
  [aux_sym_unquoted_string_token1] = "unquoted_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_quoted_string_token1] = "double_quoted_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_quoted_string_token1] = "single_quoted_string_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_backtick_quoted_string_token1] = "backtick_quoted_string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_triple_backtick_string] = "triple_backtick_string",
  [sym_triple_double_quoted_string] = "triple_double_quoted_string",
  [sym_multiline_double_quoted_string] = "multiline_double_quoted_string",
  [sym_multiline_single_quoted_string] = "multiline_single_quoted_string",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_COLON_DASH] = ":-",
  [aux_sym_expansion_token1] = "expansion_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [aux_sym_expansion_token2] = "expansion_token2",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOLLAR] = "$",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_blank_line] = "blank_line",
  [sym_config_item] = "config_item",
  [sym__comment_line] = "_comment_line",
  [sym_comment_block] = "comment_block",
  [sym__value] = "_value",
  [sym_unquoted_string] = "unquoted_string",
  [sym_quoted_string] = "quoted_string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_backtick_quoted_string] = "backtick_quoted_string",
  [sym_multiline_string] = "multiline_string",
  [sym_expansion] = "expansion",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_block_repeat1] = "comment_block_repeat1",
  [aux_sym_unquoted_string_repeat1] = "unquoted_string_repeat1",
  [aux_sym_double_quoted_string_repeat1] = "double_quoted_string_repeat1",
  [aux_sym_single_quoted_string_repeat1] = "single_quoted_string_repeat1",
  [aux_sym_backtick_quoted_string_repeat1] = "backtick_quoted_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_blank_line_token1] = aux_sym_blank_line_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_export_keyword] = sym_export_keyword,
  [sym_key] = sym_key,
  [sym_decorator_comment] = sym_decorator_comment,
  [sym_ignored_decorator_comment] = sym_ignored_decorator_comment,
  [sym_plain_comment] = sym_plain_comment,
  [sym_divider] = sym_divider,
  [aux_sym_unquoted_string_token1] = aux_sym_unquoted_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_quoted_string_token1] = aux_sym_double_quoted_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_quoted_string_token1] = aux_sym_single_quoted_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_backtick_quoted_string_token1] = aux_sym_backtick_quoted_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_triple_backtick_string] = sym_triple_backtick_string,
  [sym_triple_double_quoted_string] = sym_triple_double_quoted_string,
  [sym_multiline_double_quoted_string] = sym_multiline_double_quoted_string,
  [sym_multiline_single_quoted_string] = sym_multiline_single_quoted_string,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [aux_sym_expansion_token1] = aux_sym_expansion_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [aux_sym_expansion_token2] = aux_sym_expansion_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_blank_line] = sym_blank_line,
  [sym_config_item] = sym_config_item,
  [sym__comment_line] = sym__comment_line,
  [sym_comment_block] = sym_comment_block,
  [sym__value] = sym__value,
  [sym_unquoted_string] = sym_unquoted_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_backtick_quoted_string] = sym_backtick_quoted_string,
  [sym_multiline_string] = sym_multiline_string,
  [sym_expansion] = sym_expansion,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_block_repeat1] = aux_sym_comment_block_repeat1,
  [aux_sym_unquoted_string_repeat1] = aux_sym_unquoted_string_repeat1,
  [aux_sym_double_quoted_string_repeat1] = aux_sym_double_quoted_string_repeat1,
  [aux_sym_single_quoted_string_repeat1] = aux_sym_single_quoted_string_repeat1,
  [aux_sym_backtick_quoted_string_repeat1] = aux_sym_backtick_quoted_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_export_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_ignored_decorator_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_divider] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unquoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_backtick_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_backtick_string] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expansion_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_config_item] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_unquoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_backtick_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [sym_expansion] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unquoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_backtick_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_command = 1,
  field_fallback = 2,
  field_key = 3,
  field_line = 4,
  field_name = 5,
  field_post_comment = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_command] = "command",
  [field_fallback] = "fallback",
  [field_key] = "key",
  [field_line] = "line",
  [field_name] = "name",
  [field_post_comment] = "post_comment",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 3},
  [12] = {.index = 18, .length = 3},
  [13] = {.index = 21, .length = 1},
  [14] = {.index = 22, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_line, 0, .inherited = true},
  [1] =
    {field_line, 0},
  [2] =
    {field_line, 0, .inherited = true},
    {field_line, 1, .inherited = true},
  [4] =
    {field_key, 0},
  [5] =
    {field_key, 1},
  [6] =
    {field_key, 0},
    {field_post_comment, 2},
  [8] =
    {field_key, 0},
    {field_value, 2},
  [10] =
    {field_key, 1},
    {field_post_comment, 3},
  [12] =
    {field_key, 1},
    {field_value, 3},
  [14] =
    {field_name, 1},
  [15] =
    {field_key, 0},
    {field_post_comment, 3},
    {field_value, 2},
  [18] =
    {field_key, 1},
    {field_post_comment, 4},
    {field_value, 3},
  [21] =
    {field_command, 1},
  [22] =
    {field_fallback, 3},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 27,
  [32] = 28,
  [33] = 29,
  [34] = 30,
  [35] = 27,
  [36] = 28,
  [37] = 29,
  [38] = 30,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 52,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 59,
  [71] = 58,
  [72] = 67,
  [73] = 73,
  [74] = 59,
  [75] = 58,
  [76] = 57,
  [77] = 63,
  [78] = 73,
  [79] = 57,
  [80] = 63,
  [81] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 32,
        '\r', 2,
        '"', 68,
        '#', 46,
        '$', 96,
        '\'', 74,
        ')', 95,
        ':', 19,
        '=', 33,
        '\\', 28,
        '`', 78,
        '}', 91,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(55);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '"') ADVANCE(68);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(74);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '$') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '$') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '"') ADVANCE(85);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '\'') ADVANCE(86);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(84);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == '"') ADVANCE(67);
      if (lookahead == '$') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '$') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '`') ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(81);
      END_STATE();
    case 17:
      if (lookahead == '\'') ADVANCE(72);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(76);
      END_STATE();
    case 18:
      if (lookahead == '(') ADVANCE(92);
      if (lookahead == '{') ADVANCE(87);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(88);
      END_STATE();
    case 20:
      if (lookahead == '`') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == '`') ADVANCE(83);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == '`') ADVANCE(21);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 23:
      if (lookahead == '`') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(94);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(90);
      END_STATE();
    case 27:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(82);
      END_STATE();
    case 29:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 32,
        '\r', 2,
        '"', 68,
        '#', 46,
        '$', 18,
        '\'', 74,
        ')', 95,
        ':', 19,
        '=', 33,
        '`', 78,
        '}', 91,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == 'e') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_export_keyword);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'p') ADVANCE(35);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(38);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(40);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'x') ADVANCE(36);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_decorator_comment);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_decorator_comment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead == '#' ||
          lookahead == '@') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_decorator_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead == '@') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead == '#' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead == '@') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead == '#' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead == '#' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead == '#' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_plain_comment);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_plain_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_divider);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '\t') ADVANCE(55);
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(73);
      if (lookahead == '`') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '#') ADVANCE(15);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '"') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '#') ADVANCE(15);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '#') ADVANCE(15);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '`') ADVANCE(83);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '#') ADVANCE(23);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '`') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '`') ADVANCE(62);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '#') ADVANCE(23);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead == '`') ADVANCE(64);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '#') ADVANCE(23);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(10);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_single_quoted_string_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_single_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(20);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(66);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_backtick_quoted_string_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_backtick_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_triple_backtick_string);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_triple_double_quoted_string);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_multiline_double_quoted_string);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_multiline_single_quoted_string);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_expansion_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_expansion_token2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '(') ADVANCE(92);
      if (lookahead == '{') ADVANCE(87);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 30},
  [26] = {.lex_state = 30},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 16},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 17},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 17},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 17},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 24},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 25},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 26},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 24},
  [78] = {.lex_state = 26},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 24},
  [81] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_blank_line_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [sym_decorator_comment] = ACTIONS(1),
    [sym_ignored_decorator_comment] = ACTIONS(1),
    [sym_plain_comment] = ACTIONS(1),
    [sym_divider] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_triple_backtick_string] = ACTIONS(1),
    [sym_triple_double_quoted_string] = ACTIONS(1),
    [sym_multiline_double_quoted_string] = ACTIONS(1),
    [sym_multiline_single_quoted_string] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_blank_line] = STATE(4),
    [sym_config_item] = STATE(4),
    [sym__comment_line] = STATE(56),
    [sym_comment_block] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_comment_block_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_blank_line_token1] = ACTIONS(5),
    [sym_export_keyword] = ACTIONS(7),
    [sym_key] = ACTIONS(9),
    [sym_decorator_comment] = ACTIONS(11),
    [sym_ignored_decorator_comment] = ACTIONS(13),
    [sym_plain_comment] = ACTIONS(13),
    [sym_divider] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      aux_sym_blank_line_token1,
    ACTIONS(21), 1,
      aux_sym_unquoted_string_token1,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    STATE(64), 1,
      sym__comment_line,
    ACTIONS(19), 3,
      sym_decorator_comment,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(51), 3,
      sym_double_quoted_string,
      sym_single_quoted_string,
      sym_backtick_quoted_string,
    ACTIONS(29), 4,
      sym_triple_backtick_string,
      sym_triple_double_quoted_string,
      sym_multiline_double_quoted_string,
      sym_multiline_single_quoted_string,
    STATE(40), 4,
      sym__value,
      sym_unquoted_string,
      sym_quoted_string,
      sym_multiline_string,
  [41] = 10,
    ACTIONS(21), 1,
      aux_sym_unquoted_string_token1,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(31), 1,
      aux_sym_blank_line_token1,
    STATE(61), 1,
      sym__comment_line,
    ACTIONS(33), 3,
      sym_decorator_comment,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(51), 3,
      sym_double_quoted_string,
      sym_single_quoted_string,
      sym_backtick_quoted_string,
    ACTIONS(29), 4,
      sym_triple_backtick_string,
      sym_triple_double_quoted_string,
      sym_multiline_double_quoted_string,
      sym_multiline_single_quoted_string,
    STATE(39), 4,
      sym__value,
      sym_unquoted_string,
      sym_quoted_string,
      sym_multiline_string,
  [82] = 10,
    ACTIONS(5), 1,
      aux_sym_blank_line_token1,
    ACTIONS(7), 1,
      sym_export_keyword,
    ACTIONS(9), 1,
      sym_key,
    ACTIONS(11), 1,
      sym_decorator_comment,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_divider,
    STATE(6), 1,
      aux_sym_comment_block_repeat1,
    STATE(56), 1,
      sym__comment_line,
    ACTIONS(13), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(5), 4,
      sym_blank_line,
      sym_config_item,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [117] = 10,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_blank_line_token1,
    ACTIONS(44), 1,
      sym_export_keyword,
    ACTIONS(47), 1,
      sym_key,
    ACTIONS(50), 1,
      sym_decorator_comment,
    ACTIONS(56), 1,
      sym_divider,
    STATE(6), 1,
      aux_sym_comment_block_repeat1,
    STATE(56), 1,
      sym__comment_line,
    ACTIONS(53), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(5), 4,
      sym_blank_line,
      sym_config_item,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [152] = 4,
    STATE(7), 1,
      aux_sym_comment_block_repeat1,
    STATE(56), 1,
      sym__comment_line,
    ACTIONS(61), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [171] = 6,
    ACTIONS(65), 1,
      sym_key,
    ACTIONS(67), 1,
      sym_decorator_comment,
    STATE(7), 1,
      aux_sym_comment_block_repeat1,
    STATE(56), 1,
      sym__comment_line,
    ACTIONS(70), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(63), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_divider,
  [194] = 6,
    ACTIONS(77), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(79), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DOLLAR,
    ACTIONS(73), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(75), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(9), 2,
      sym_expansion,
      aux_sym_unquoted_string_repeat1,
  [216] = 6,
    ACTIONS(77), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(79), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DOLLAR,
    ACTIONS(83), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(85), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(10), 2,
      sym_expansion,
      aux_sym_unquoted_string_repeat1,
  [238] = 6,
    ACTIONS(91), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(94), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(97), 1,
      anon_sym_DOLLAR,
    ACTIONS(87), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(89), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    STATE(10), 2,
      sym_expansion,
      aux_sym_unquoted_string_repeat1,
  [260] = 2,
    ACTIONS(102), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(100), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [273] = 2,
    ACTIONS(106), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [286] = 2,
    ACTIONS(110), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [299] = 2,
    ACTIONS(114), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [312] = 2,
    ACTIONS(118), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [325] = 2,
    ACTIONS(122), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [338] = 6,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
    ACTIONS(128), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(130), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(132), 1,
      anon_sym_DOLLAR,
    ACTIONS(126), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    STATE(23), 2,
      sym_expansion,
      aux_sym_double_quoted_string_repeat1,
  [359] = 6,
    ACTIONS(134), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(140), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    ACTIONS(136), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    STATE(24), 2,
      sym_expansion,
      aux_sym_backtick_quoted_string_repeat1,
  [380] = 2,
    ACTIONS(146), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [393] = 2,
    ACTIONS(150), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [406] = 6,
    ACTIONS(128), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(130), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(132), 1,
      anon_sym_DOLLAR,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    STATE(17), 2,
      sym_expansion,
      aux_sym_double_quoted_string_repeat1,
  [427] = 6,
    ACTIONS(138), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(140), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    ACTIONS(156), 1,
      anon_sym_BQUOTE,
    ACTIONS(158), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    STATE(18), 2,
      sym_expansion,
      aux_sym_backtick_quoted_string_repeat1,
  [448] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(168), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(171), 1,
      anon_sym_DOLLAR,
    ACTIONS(162), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    STATE(23), 2,
      sym_expansion,
      aux_sym_double_quoted_string_repeat1,
  [469] = 6,
    ACTIONS(174), 1,
      anon_sym_BQUOTE,
    ACTIONS(179), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(182), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(185), 1,
      anon_sym_DOLLAR,
    ACTIONS(176), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    STATE(24), 2,
      sym_expansion,
      aux_sym_backtick_quoted_string_repeat1,
  [490] = 2,
    ACTIONS(190), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [503] = 2,
    ACTIONS(194), 3,
      sym_key,
      sym_ignored_decorator_comment,
      sym_plain_comment,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_export_keyword,
      sym_decorator_comment,
      sym_divider,
  [516] = 2,
    ACTIONS(198), 3,
      sym_ignored_decorator_comment,
      sym_plain_comment,
      anon_sym_DOLLAR,
    ACTIONS(196), 4,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
  [528] = 2,
    ACTIONS(202), 3,
      sym_ignored_decorator_comment,
      sym_plain_comment,
      anon_sym_DOLLAR,
    ACTIONS(200), 4,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
  [540] = 2,
    ACTIONS(206), 3,
      sym_ignored_decorator_comment,
      sym_plain_comment,
      anon_sym_DOLLAR,
    ACTIONS(204), 4,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
  [552] = 2,
    ACTIONS(210), 3,
      sym_ignored_decorator_comment,
      sym_plain_comment,
      anon_sym_DOLLAR,
    ACTIONS(208), 4,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
  [564] = 2,
    ACTIONS(196), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(198), 4,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [575] = 2,
    ACTIONS(200), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(202), 4,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [586] = 2,
    ACTIONS(204), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(206), 4,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [597] = 2,
    ACTIONS(208), 2,
      aux_sym_double_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(210), 4,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [608] = 2,
    ACTIONS(196), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(198), 4,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [619] = 2,
    ACTIONS(200), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(202), 4,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [630] = 2,
    ACTIONS(204), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(206), 4,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [641] = 2,
    ACTIONS(208), 2,
      aux_sym_backtick_quoted_string_token1,
      sym_escape_sequence,
    ACTIONS(210), 4,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      anon_sym_DOLLAR,
  [652] = 4,
    ACTIONS(212), 1,
      aux_sym_blank_line_token1,
    ACTIONS(214), 1,
      sym_decorator_comment,
    STATE(62), 1,
      sym__comment_line,
    ACTIONS(216), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [666] = 4,
    ACTIONS(218), 1,
      aux_sym_blank_line_token1,
    ACTIONS(220), 1,
      sym_decorator_comment,
    STATE(65), 1,
      sym__comment_line,
    ACTIONS(222), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [680] = 2,
    ACTIONS(224), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(226), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [689] = 2,
    ACTIONS(228), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(230), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [698] = 2,
    ACTIONS(232), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(234), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [707] = 3,
    ACTIONS(236), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      aux_sym_single_quoted_string_repeat1,
    ACTIONS(238), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
  [718] = 2,
    ACTIONS(241), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(243), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [727] = 2,
    ACTIONS(245), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(247), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [736] = 3,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
    STATE(49), 1,
      aux_sym_single_quoted_string_repeat1,
    ACTIONS(251), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
  [747] = 2,
    ACTIONS(253), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(255), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [756] = 3,
    ACTIONS(257), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      aux_sym_single_quoted_string_repeat1,
    ACTIONS(259), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
  [767] = 2,
    ACTIONS(261), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(263), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [776] = 2,
    ACTIONS(265), 2,
      aux_sym_blank_line_token1,
      sym_decorator_comment,
    ACTIONS(267), 2,
      sym_ignored_decorator_comment,
      sym_plain_comment,
  [785] = 2,
    ACTIONS(269), 1,
      anon_sym_COLON_DASH,
    ACTIONS(271), 1,
      anon_sym_RBRACE,
  [792] = 2,
    ACTIONS(273), 1,
      anon_sym_COLON_DASH,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
  [799] = 2,
    ACTIONS(277), 1,
      anon_sym_COLON_DASH,
    ACTIONS(279), 1,
      anon_sym_RBRACE,
  [806] = 1,
    ACTIONS(281), 1,
      anon_sym_EQ,
  [810] = 1,
    ACTIONS(283), 1,
      aux_sym_blank_line_token1,
  [814] = 1,
    ACTIONS(285), 1,
      sym_identifier,
  [818] = 1,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
  [822] = 1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [826] = 1,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
  [830] = 1,
    ACTIONS(293), 1,
      aux_sym_blank_line_token1,
  [834] = 1,
    ACTIONS(295), 1,
      aux_sym_blank_line_token1,
  [838] = 1,
    ACTIONS(297), 1,
      aux_sym_expansion_token2,
  [842] = 1,
    ACTIONS(299), 1,
      aux_sym_blank_line_token1,
  [846] = 1,
    ACTIONS(301), 1,
      aux_sym_blank_line_token1,
  [850] = 1,
    ACTIONS(303), 1,
      anon_sym_EQ,
  [854] = 1,
    ACTIONS(305), 1,
      sym_identifier,
  [858] = 1,
    ACTIONS(307), 1,
      sym_identifier,
  [862] = 1,
    ACTIONS(309), 1,
      sym_key,
  [866] = 1,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
  [870] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [874] = 1,
    ACTIONS(315), 1,
      sym_identifier,
  [878] = 1,
    ACTIONS(317), 1,
      aux_sym_expansion_token1,
  [882] = 1,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
  [886] = 1,
    ACTIONS(321), 1,
      anon_sym_RBRACE,
  [890] = 1,
    ACTIONS(323), 1,
      sym_identifier,
  [894] = 1,
    ACTIONS(325), 1,
      aux_sym_expansion_token2,
  [898] = 1,
    ACTIONS(327), 1,
      aux_sym_expansion_token1,
  [902] = 1,
    ACTIONS(329), 1,
      sym_identifier,
  [906] = 1,
    ACTIONS(331), 1,
      aux_sym_expansion_token2,
  [910] = 1,
    ACTIONS(333), 1,
      aux_sym_expansion_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 152,
  [SMALL_STATE(7)] = 171,
  [SMALL_STATE(8)] = 194,
  [SMALL_STATE(9)] = 216,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 260,
  [SMALL_STATE(12)] = 273,
  [SMALL_STATE(13)] = 286,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 312,
  [SMALL_STATE(16)] = 325,
  [SMALL_STATE(17)] = 338,
  [SMALL_STATE(18)] = 359,
  [SMALL_STATE(19)] = 380,
  [SMALL_STATE(20)] = 393,
  [SMALL_STATE(21)] = 406,
  [SMALL_STATE(22)] = 427,
  [SMALL_STATE(23)] = 448,
  [SMALL_STATE(24)] = 469,
  [SMALL_STATE(25)] = 490,
  [SMALL_STATE(26)] = 503,
  [SMALL_STATE(27)] = 516,
  [SMALL_STATE(28)] = 528,
  [SMALL_STATE(29)] = 540,
  [SMALL_STATE(30)] = 552,
  [SMALL_STATE(31)] = 564,
  [SMALL_STATE(32)] = 575,
  [SMALL_STATE(33)] = 586,
  [SMALL_STATE(34)] = 597,
  [SMALL_STATE(35)] = 608,
  [SMALL_STATE(36)] = 619,
  [SMALL_STATE(37)] = 630,
  [SMALL_STATE(38)] = 641,
  [SMALL_STATE(39)] = 652,
  [SMALL_STATE(40)] = 666,
  [SMALL_STATE(41)] = 680,
  [SMALL_STATE(42)] = 689,
  [SMALL_STATE(43)] = 698,
  [SMALL_STATE(44)] = 707,
  [SMALL_STATE(45)] = 718,
  [SMALL_STATE(46)] = 727,
  [SMALL_STATE(47)] = 736,
  [SMALL_STATE(48)] = 747,
  [SMALL_STATE(49)] = 756,
  [SMALL_STATE(50)] = 767,
  [SMALL_STATE(51)] = 776,
  [SMALL_STATE(52)] = 785,
  [SMALL_STATE(53)] = 792,
  [SMALL_STATE(54)] = 799,
  [SMALL_STATE(55)] = 806,
  [SMALL_STATE(56)] = 810,
  [SMALL_STATE(57)] = 814,
  [SMALL_STATE(58)] = 818,
  [SMALL_STATE(59)] = 822,
  [SMALL_STATE(60)] = 826,
  [SMALL_STATE(61)] = 830,
  [SMALL_STATE(62)] = 834,
  [SMALL_STATE(63)] = 838,
  [SMALL_STATE(64)] = 842,
  [SMALL_STATE(65)] = 846,
  [SMALL_STATE(66)] = 850,
  [SMALL_STATE(67)] = 854,
  [SMALL_STATE(68)] = 858,
  [SMALL_STATE(69)] = 862,
  [SMALL_STATE(70)] = 866,
  [SMALL_STATE(71)] = 870,
  [SMALL_STATE(72)] = 874,
  [SMALL_STATE(73)] = 878,
  [SMALL_STATE(74)] = 882,
  [SMALL_STATE(75)] = 886,
  [SMALL_STATE(76)] = 890,
  [SMALL_STATE(77)] = 894,
  [SMALL_STATE(78)] = 898,
  [SMALL_STATE(79)] = 902,
  [SMALL_STATE(80)] = 906,
  [SMALL_STATE(81)] = 910,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 1, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_block, 1, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 3),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 3), SHIFT_REPEAT(56),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 3), SHIFT_REPEAT(56),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquoted_string, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquoted_string, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquoted_string, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquoted_string, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unquoted_string_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unquoted_string_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unquoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unquoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unquoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 4, 0, 7),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 4, 0, 7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 5, 0, 9),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 5, 0, 9),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 4, 0, 5),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 4, 0, 5),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 4, 0, 6),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 4, 0, 6),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 3, 0, 4),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 3, 0, 4),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 5, 0, 8),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 5, 0, 8),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_block_repeat1, 2, 0, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_backtick_quoted_string_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_backtick_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backtick_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backtick_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_backtick_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 5, 0, 11),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 5, 0, 11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_item, 6, 0, 12),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_item, 6, 0, 12),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 2, 0, 10),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 2, 0, 10),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 3, 0, 10),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 3, 0, 10),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 3, 0, 13),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 3, 0, 13),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 5, 0, 14),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 5, 0, 14),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quoted_string, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quoted_string, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_string, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_quoted_string, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_quoted_string_repeat1, 2, 0, 0),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_single_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_quoted_string, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backtick_quoted_string, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_string, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_quoted_string, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_string, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_string, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_quoted_string, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backtick_quoted_string, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [291] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_envspec(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
